font_family      Ioskeley Mono
font_size 15.0
paste_actions confirm
background_opacity 1
background #121212
confirm_os_window_close 0
window_padding_width 2

allow_remote_control socket-only
listen_on unix:/tmp/kitty
